language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
  - gem install bundler
  - nvm install node
  - bundle
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: ENV["heroku_api_key"]
  # api_key: ENV["secure_travis_key"]
  app: walk-safe-backend
  run: rails db:migrate
  on:
    repo: Walk-Safe/walk-safe-backend
    branch: main
  skip_cleanup: 'true'
